name: 构建和发布

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取所有标签以便正确生成版本号

      - name: 设置 Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zip

      - name: 构建所有架构
        env:
          CGO_ENABLED: 1
        run: make all-arch

      - name: 创建发布文件
        run: make releases

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/*

  release:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: bin

      - name: 获取当前日期
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: 创建 Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref == 'refs/heads/main' && format('release-{0}', steps.date.outputs.date) || github.ref }}
          release_name: ${{ github.ref == 'refs/heads/main' && format('Release {0}', steps.date.outputs.date) || github.ref }}
          draft: false
          prerelease: ${{ github.ref == 'refs/heads/main' }}

      - name: 上传 Release 资产
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: bin/*
          tag_name: ${{ github.ref == 'refs/heads/main' && format('release-{0}', steps.date.outputs.date) || github.ref }}
          prerelease: ${{ github.ref == 'refs/heads/main' }}
